name: Build 

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_win:
  
    strategy:
      matrix:
          targetplatform: [x64, x86]

    runs-on:  windows-2019
    
    steps:
      - name: Checkout src
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
        
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
         
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.7        
          
      - name: Modify version number
        run: "sed -i 's/Version: 0.0.0/version:  ${{ steps.gitversion.outputs.fullSemVer }}/' reaper_csurf_integrator/res.rc"
        
      - name: Print File
        run: "cat reaper_csurf_integrator/res.rc"
      
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Build src
        run: |
          msbuild visualstudio\reaper_csurf_integrator.vcxproj `
          -verbosity:minimal `
          -t:rebuild `
          /p:Configuration=Release `
          /p:Platform=${{ matrix.targetplatform }}    
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Extensions
          path: reaper_csurf_integrator*.dll
          

  build_macos:

    runs-on:  macos-latest
    
    steps:
    
      - name: Checkout src
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
        
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.7        
          
      - name: Modify version number
        run: "sed -i '' 's/Version: 0.0.0/version:  ${{ steps.gitversion.outputs.fullSemVer }}/' reaper_csurf_integrator/res.rc_mac_dlg"
        
      - name: Print File
        run: "cat reaper_csurf_integrator/res.rc_mac_dlg"
      
      - name: Setup XCode Build
        uses: mxcl/xcodebuild@v1
        with:
          platform: macOS
          action: build 
          configuration: Release
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Extensions  
          path: reaper_csurf_integrator.dylib